// Mocks generated by Mockito 5.2.0 from annotations
// in ecommerce/test/screens/products/application/products_cubit_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:ecommerce/screens/products/domain/product.dart' as _i5;
import 'package:ecommerce/screens/products/infrastructure/products_facade.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeEither_0<L, R> extends _i1.Fake implements _i2.Either<L, R> {}

/// A class which mocks [ProductsFacade].
///
/// See the documentation for Mockito's code generation for more information.
class MockProductsFacade extends _i1.Mock implements _i3.ProductsFacade {
  MockProductsFacade() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<String, List<_i5.Product>>> fetchProducts(
          {String? category}) =>
      (super.noSuchMethod(
              Invocation.method(#fetchProducts, [], {#category: category}),
              returnValue: Future<_i2.Either<String, List<_i5.Product>>>.value(
                  _FakeEither_0<String, List<_i5.Product>>()))
          as _i4.Future<_i2.Either<String, List<_i5.Product>>>);
}
