// Mocks generated by Mockito 5.2.0 from annotations
// in ecommerce/test/screens/login/infrastructure/remote/login_api_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i3;

import 'package:ecommerce/shared/http_client/http_client.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

/// A class which mocks [HttpClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockHttpClient extends _i1.Mock implements _i2.HttpClient {
  MockHttpClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<T?> get<T>({String? path}) =>
      (super.noSuchMethod(Invocation.method(#get, [], {#path: path}),
          returnValue: Future<T?>.value()) as _i3.Future<T?>);
  @override
  _i3.Future<T?> post<T>({String? path, Map<String, dynamic>? body}) => (super
      .noSuchMethod(Invocation.method(#post, [], {#path: path, #body: body}),
          returnValue: Future<T?>.value()) as _i3.Future<T?>);
}
