// Mocks generated by Mockito 5.2.0 from annotations
// in ecommerce/test/screens/cart/infrastructure/cart_facade_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i4;

import 'package:ecommerce/screens/cart/infrastructure/local/cart_product_storage_provider.dart'
    as _i3;
import 'package:ecommerce/screens/products/domain/product.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _Fake$ProductCopyWith_0<$Res> extends _i1.Fake
    implements _i2.$ProductCopyWith<$Res> {}

/// A class which mocks [CartProductStorageProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockCartProductStorageProvider extends _i1.Mock
    implements _i3.CartProductStorageProvider {
  MockCartProductStorageProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<void> saveProduct({int? id, Map<String, dynamic>? product}) =>
      (super.noSuchMethod(
          Invocation.method(#saveProduct, [], {#id: id, #product: product}),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i4.Future<void>);
  @override
  _i4.Future<void> removeProduct({int? id}) =>
      (super.noSuchMethod(Invocation.method(#removeProduct, [], {#id: id}),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i4.Future<void>);
  @override
  _i4.Future<List<Map<String, dynamic>>> fetchProducts() => (super.noSuchMethod(
      Invocation.method(#fetchProducts, []),
      returnValue: Future<List<Map<String, dynamic>>>.value(
          <Map<String, dynamic>>[])) as _i4.Future<List<Map<String, dynamic>>>);
}

/// A class which mocks [Product].
///
/// See the documentation for Mockito's code generation for more information.
class MockProduct extends _i1.Mock implements _i2.Product {
  MockProduct() {
    _i1.throwOnMissingStub(this);
  }

  @override
  int get id =>
      (super.noSuchMethod(Invocation.getter(#id), returnValue: 0) as int);
  @override
  String get title =>
      (super.noSuchMethod(Invocation.getter(#title), returnValue: '')
          as String);
  @override
  String get desciption =>
      (super.noSuchMethod(Invocation.getter(#desciption), returnValue: '')
          as String);
  @override
  double get price =>
      (super.noSuchMethod(Invocation.getter(#price), returnValue: 0.0)
          as double);
  @override
  String get image =>
      (super.noSuchMethod(Invocation.getter(#image), returnValue: '')
          as String);
  @override
  _i2.$ProductCopyWith<_i2.Product> get copyWith =>
      (super.noSuchMethod(Invocation.getter(#copyWith),
              returnValue: _Fake$ProductCopyWith_0<_i2.Product>())
          as _i2.$ProductCopyWith<_i2.Product>);
  @override
  Map<String, dynamic> toJson() =>
      (super.noSuchMethod(Invocation.method(#toJson, []),
          returnValue: <String, dynamic>{}) as Map<String, dynamic>);
}
